const Productos = [
    {
        id: 1,
        nombre: 'budin de mandarina',
        precio: 300,
        imagen: 'https://img-global.cpcdn.com/recipes/da9b8ae10799e873/1200x630cq70/photo.jpg',
        categoria: 'Budines'
    },
    {
        id: 2,
        nombre: 'alfajores de maicena',
        precio: 400,
        imagen: 'https://www.elmundoeats.com/wp-content/uploads/2021/07/FP2-Argentine-alfajores-on-a-rack-500x500.jpg',
        categoria: 'Otras especialidades'
    },
    {
        id: 3,
        nombre: 'pasta frola de membrillo',
        precio: 350,
        imagen: 'https://delosabuelostandil.com.ar/wp-content/uploads/2021/06/pastafrola-membrillo.jpg',
        categoria: 'Pasta frola'
    },
    {
        id: 4,
        nombre: 'pasta frola de batata',
        precio: 350,
        imagen: 'https://truffle-assets.imgix.net/f352f18a-pasta-frola-mixta_l_thumb.jpg',
        categoria: 'Pasta frola'
    },
    {
        id: 5,
        nombre: 'bizcochuelo marmolado',
        precio: 400,
        imagen: 'https://bizcochuelo.info/wp-content/uploads/2020/06/Bizcocho-marmolado.png',
        categoria: 'Bizcochuelo'
    }
]

export default Productos; 